export async function GET() {
  const tickets = [
    {
      id: 't-1001',
      title: 'Cannot connect to VPN',
      description: 'User reports intermittent VPN connectivity errors.',
      priority: 'High',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-10-31T14:05:00Z',
    },
    {
      id: 't-1002',
      title: 'Email not syncing on mobile',
      description: 'Exchange account stuck on updating for iOS Mail.',
      priority: 'Medium',
      status: 'In Progress',
      assignee: 'Jordan',
      updatedAt: '2025-10-25T05:12:00Z',
    },
    {
      id: 't-1003',
      title: 'Laptop battery drains quickly',
      description: 'Battery drops from 100% to 20% in 2 hours.',
      priority: 'Low',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-10-22T12:30:00Z',
    },
    {
      id: 't-1004',
      title: 'Okta MFA prompts repeatedly',
      description: 'User receives MFA prompts every few minutes.',
      priority: 'Critical',
      status: 'On Hold',
      assignee: 'Priya',
      updatedAt: '2025-10-28T09:24:00Z',
    },
    {
      id: 't-1005',
      title: 'Printer not responding on Floor 3',
      description: 'Queue shows jobs timing out.',
      priority: 'Medium',
      status: 'Open',
      assignee: 'Morgan',
      updatedAt: '2025-10-13T07:00:00Z',
    },
    {
      id: 't-1006',
      title: 'Teams screen share fails',
      description: 'Sharing starts and immediately stops.',
      priority: 'High',
      status: 'Open',
      assignee: 'Alex',
      updatedAt: '2025-10-03T06:00:00Z',
    },
    {
      id: 't-1007',
      title: 'New hire account provisioning',
      description: 'Create accounts and assign baseline groups.',
      priority: 'Critical',
      status: 'In Progress',
      assignee: 'Morgan',
      updatedAt: '2025-10-12T04:45:00Z',
    },
    {
      id: 't-1008',
      title: 'Wi-Fi drops in Conference Room A',
      description: 'Signal fluctuates during large meetings.',
      priority: 'Medium',
      status: 'Open',
      assignee: 'Jessica',
      updatedAt: '2025-10-15T08:15:00Z',
    },
    {
      id: 't-1009',
      title: 'Locked out of Salesforce',
      description: 'User cannot complete MFA push.',
      priority: 'High',
      status: 'Resolved',
      assignee: 'Sam',
      updatedAt: '2025-10-22T10:05:00Z',
    },
    {
      id: 't-1010',
      title: 'Zoom audio echoes',
      description: 'Echoes when unmuted by multiple attendees.',
      priority: 'Low',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-10-27T06:00:00Z',
    },
    {
      id: 't-1011',
      title: 'Shared drive permissions',
      description: 'Access denied for new project members.',
      priority: 'Medium',
      status: 'Open',
      assignee: 'Priya',
      updatedAt: '2025-10-30T14:50:00Z',
    },
    {
      id: 't-1012',
      title: 'Slack notifications delayed',
      description: 'Messages appear several minutes late.',
      priority: 'Low',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-10-15T05:55:00Z',
    },
    {
      id: 't-1013',
      title: 'macOS update failing',
      description: 'Install stalls at 20%.',
      priority: 'Critical',
      status: 'Open',
      assignee: 'Jordan',
      updatedAt: '2025-10-25T03:40:00Z',
    },
    {
      id: 't-1014',
      title: 'SFTP key rotation',
      description: 'Rotate keys for finance integration.',
      priority: 'High',
      status: 'In Progress',
      assignee: 'Santi',
      updatedAt: '2025-10-23T09:05:00Z',
    },
    {
      id: 't-1015',
      title: 'Calendar invites not delivered',
      description: 'Invites arrive hours later.',
      priority: 'Medium',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-10-13T08:25:00Z',
    },
  ];
  return Response.json(tickets);
}
